pois:
  poi0:
    label: "ZERO"
    pose: [[+1.0, +3.0, 0.0], [0.707, 0.0, 0.0, 0.707]]
  poi1:
    label: "ONE"
    pose: [[+1.0, +8.0, 0.0], [0.707, 0.0, 0.0, 0.707]]
  poi2:
    label: "TWO"
    pose: [[+4.0, +3.0, 0.0], [0.707, 0.0, 0.0, 0.707]]
  poi3:
    label: "THREE"
    pose: [[-4.0, +6.0, 0.0], [0.707, 0.0, 0.0, 0.707]]

